word_list_1 = [
    "lion",
    "moon",
    "sun",
    "cake",
    "cave",
    "dark",
    "earth",
    "hello",
    "kite",
    "saga",
    "image",
    "banana",
    "baby",
    "College"
    ]
word_list_2 = [
    "annual",
    "classic",
    "diversity",
    "evident",
    "export",
    "finance",
    "hybrid",
    "income",
    "parameter",
    "reliance",
    "sector",
    "tradition",
    "Japanese",
    "Newsletter"
    ]
word_list_3 = [
    "Reflection",
    "Pedagogy",
    "important",
    "excellent",
    "friendship",
    "chickenpox",
    "submission",
    "experience",
    "dedication",
    "dictionary",
    "investment",
    "confidence",
    "transformation",
    "acknowledgement"
    ]
